from pathlib import Path
import unittest


PROJECT_ROOT = Path(__file__).resolve().parents[1]
STATIC_DIRECTORY = PROJECT_ROOT / "herdr_web" / "static"


class FrontendContractTests(unittest.TestCase):
    def test_terminal_output_uses_supported_xterm_write_queue(self) -> None:
        application = (STATIC_DIRECTORY / "app.js").read_text(encoding="utf-8")

        self.assertNotIn("_core.writeSync", application)
        self.assertIn("activeTerminal.write(bytes, () =>", application)
        self.assertIn("noteParsedOutput(flow, bytes.length)", application)

    def test_mouse_motion_is_coalesced_without_delaying_keys(self) -> None:
        application = (STATIC_DIRECTORY / "app.js").read_text(encoding="utf-8")

        self.assertIn("isDisposableMouseMotion(data)", application)
        self.assertIn("pendingMouseMotion = data", application)
        self.assertIn("queuePendingMouseMotion();\n      inputBuffer.append(data)", application)
        self.assertIn("MOUSE_MOTION_INTERVAL_MS = 16", application)

    def test_webgl_renderer_has_dom_fallback(self) -> None:
        application = (STATIC_DIRECTORY / "app.js").read_text(encoding="utf-8")
        vendor = STATIC_DIRECTORY / "vendor"

        self.assertIn("import './vendor/xterm-addon-webgl.js'", application)
        self.assertIn("activeTerminal.loadAddon(addon)", application)
        self.assertIn("addon.onContextLoss", application)
        self.assertIn("addon?.dispose()", application)
        self.assertTrue((vendor / "xterm-addon-webgl.js").is_file())
        self.assertTrue((vendor / "xterm-addon-webgl.LICENSE").is_file())

    def test_desktop_header_keeps_navigation_left_and_modes_right(self) -> None:
        document = (STATIC_DIRECTORY / "index.html").read_text(encoding="utf-8")
        stylesheet = (STATIC_DIRECTORY / "style.css").read_text(encoding="utf-8")

        self.assertLess(document.index('id="backend-name"'), document.index('id="back"'))
        self.assertLess(document.index('id="back"'), document.index('id="view-modes"'))
        self.assertLess(document.index('id="view-modes"'), document.index('id="telemetry"'))
        self.assertIn("#view-modes { display: flex; flex: 0 0 auto;", stylesheet)
        self.assertIn("margin-left: auto;", stylesheet)
        self.assertIn("#back {", stylesheet)
        self.assertIn("flex: 0 0 auto;", stylesheet)
        self.assertNotIn("#back { margin-left: auto; }", stylesheet)

    def test_desktop_panes_keep_xterm_focus_after_output(self) -> None:
        application = (STATIC_DIRECTORY / "app.js").read_text(encoding="utf-8")
        helper_start = application.index("  function syncPaneKeyboardHelper(pane)")
        helper_end = application.index("  function focusPaneKeyboard(pane)", helper_start)
        helper_sync = application[helper_start:helper_end]

        self.assertIn("if (!mobileTarget) return;", helper_sync)
        self.assertLess(
            helper_sync.index("if (!mobileTarget) return;"),
            helper_sync.index("helper.blur();"),
        )
        self.assertIn(
            "if (!mobileQuery.matches) paneTerminals.get(streamId)?.terminal.focus();",
            application,
        )

    def test_terminal_chrome_uses_the_measured_cell_grid(self) -> None:
        application = (STATIC_DIRECTORY / "app.js").read_text(encoding="utf-8")
        stylesheet = (STATIC_DIRECTORY / "style.css").read_text(encoding="utf-8")

        self.assertIn("function syncTerminalGridMetrics(activeTerminal)", application)
        self.assertIn("bounds.width / activeTerminal.cols", application)
        self.assertIn("bounds.height / activeTerminal.rows", application)
        self.assertIn("fitPaneTerminal(record);", application)
        self.assertIn("scrollback: 0", application)
        self.assertIn("--terminal-cell-width", stylesheet)
        self.assertIn("--terminal-cell-height", stylesheet)
        self.assertIn("height: var(--terminal-row-3);", stylesheet)
        self.assertIn(".xterm .xterm-viewport { background-color: var(--theme-background); }", stylesheet)
        self.assertIn(".pane-terminal .xterm-viewport { overflow-y: hidden; }", stylesheet)

    def test_mobile_navigation_uses_structured_backend_api(self) -> None:
        application = (STATIC_DIRECTORY / "app.js").read_text(encoding="utf-8")
        document = (STATIC_DIRECTORY / "index.html").read_text(encoding="utf-8")
        stylesheet = (STATIC_DIRECTORY / "style.css").read_text(encoding="utf-8")

        self.assertIn("backendApiUrl(backend, 'navigation')", application)
        self.assertIn("backendApiUrl(currentBackend, 'focus')", application)
        self.assertIn('id="mobile-toolbar"', document)
        self.assertIn('data-sheet="spaces"', document)
        self.assertIn('data-sheet="tabs"', document)
        self.assertIn('data-sheet="agents"', document)
        self.assertIn('data-sheet="more"', document)
        self.assertIn("env(safe-area-inset-bottom)", stylesheet)
        self.assertIn("@media (max-width: 700px)", stylesheet)

    def test_mobile_sheet_uses_an_expandable_flat_animated_tree(self) -> None:
        application = (STATIC_DIRECTORY / "app.js").read_text(encoding="utf-8")
        document = (STATIC_DIRECTORY / "index.html").read_text(encoding="utf-8")
        stylesheet = (STATIC_DIRECTORY / "style.css").read_text(encoding="utf-8")

        self.assertIn('class="sheet-close-icon"', document)
        self.assertIn('id="sheet-sessions"', document)
        self.assertIn('class="sheet-sessions-icon" viewBox="6 4 12 16"', document)
        self.assertIn('<path d="m15 18-6-6 6-6"></path>', document)
        self.assertNotIn('aria-label="Close navigation">Close</button>', document)
        self.assertIn("tree.className = 'sheet-tree'", application)
        self.assertIn("function togglePaneBrowseBranch(kind, targetId)", application)
        self.assertIn("function paneBrowseChevronIcon()", application)
        self.assertIn("document.createElementNS(namespace, 'svg')", application)
        self.assertIn("icon.setAttribute('viewBox', '6 4 12 16')", application)
        self.assertIn("path.setAttribute('d', 'm9 18 6-6-6-6')", application)
        self.assertIn("paneBrowseExpandedWorkspaces", application)
        self.assertIn("paneBrowseExpandedTabs", application)
        self.assertIn("tabPanes.length > 1 && tabExpanded", application)
        self.assertIn("? () => togglePaneBrowseBranch('tab', tab.tab_id)", application)
        self.assertIn(": () => selectPaneTab(tab.tab_id)", application)
        self.assertNotIn("const tabDetail", application)
        self.assertNotIn("const paneDetail", application)
        self.assertIn("sheetSessions.addEventListener('click', () => showPicker())", application)
        self.assertIn("MIN_MOBILE_TERMINAL_FONT_SIZE = 10", application)
        self.assertIn("MAX_MOBILE_TERMINAL_FONT_SIZE = 24", application)
        self.assertIn("mobileSheet.dataset.state = 'closing'", application)
        self.assertIn("mobileSheet.dataset.state = animate ? 'opening' : 'open'", application)
        self.assertIn("MOBILE_SHEET_ANIMATION_MS = 240", application)
        self.assertIn(".sheet-item {", stylesheet)
        self.assertIn("border-radius: 0;", stylesheet)
        self.assertIn(".sheet-tree-branch[aria-expanded=\"true\"] .sheet-tree-chevron", stylesheet)
        self.assertIn(".sheet-tree-chevron {", stylesheet)
        self.assertIn("flex: 0 0 .875rem;", stylesheet)
        self.assertIn("transform: translateY(1px) rotate(90deg);", stylesheet)
        self.assertNotIn(".sheet-item-label::before", stylesheet)
        self.assertIn("nameText.className = 'sheet-item-label-text'", application)
        self.assertIn("--sheet-child-item-height: max(40px", stylesheet)
        self.assertIn("padding-left: var(--sheet-tree-indent)", stylesheet)
        self.assertIn(".sheet-tree .sheet-item { box-shadow: inset 1px 0 var(--theme-accent); }", stylesheet)
        self.assertIn("box-shadow: inset 3px 0 var(--theme-accent);", stylesheet)
        self.assertNotIn("var(--theme-accent) 12%", stylesheet)
        self.assertNotIn("var(--theme-accent) 22%", stylesheet)
        self.assertNotIn(".sheet-tree li li::before", stylesheet)
        self.assertIn("grid-template-columns: var(--terminal-row-3) minmax(0, 1fr)", stylesheet)
        self.assertIn('#mobile-sheet[data-state="open"] > section', stylesheet)
        self.assertIn("transform: translateY(calc(100% + 1px))", stylesheet)
        self.assertIn("@media (prefers-reduced-motion: reduce)", stylesheet)

    def test_mobile_uses_panes_with_touch_scrolling(self) -> None:
        application = (STATIC_DIRECTORY / "app.js").read_text(encoding="utf-8")
        document = (STATIC_DIRECTORY / "index.html").read_text(encoding="utf-8")
        stylesheet = (STATIC_DIRECTORY / "style.css").read_text(encoding="utf-8")

        self.assertIn("if (mobileQuery.matches) return 'panes'", application)
        self.assertNotIn("Open Full mode", application)
        self.assertIn("addEventListener('touchmove'", application)
        self.assertIn("touchScrollDistance > 0 ? 'up' : 'down'", application)
        self.assertIn("Math.exp(-elapsed / MOBILE_SCROLL_DECAY_MS)", application)
        self.assertIn("MOBILE_SCROLL_DECAY_MS = 240", application)
        self.assertIn("requestAnimationFrame(step)", application)
        self.assertIn("reducedMotionQuery.matches", application)
        self.assertIn("].join(' · ')", application)
        self.assertNotIn('id="pane-breadcrumb"', document)
        self.assertNotIn('id="pane-connection"', document)
        self.assertIn('d="M4 6h16M4 12h16M4 18h16"', document)
        self.assertIn('id="mobile-primary-row"', document)
        self.assertIn('id="mobile-default-row"', document)
        self.assertIn('id="mobile-navigation-row"', document)
        self.assertIn('id="mobile-modifiers"', document)
        self.assertIn('data-modifier="control"', document)
        self.assertIn('data-modifier="alt"', document)
        self.assertIn('data-modifier="shift"', document)
        self.assertIn('data-terminal-key="escape"', document)
        self.assertIn('data-terminal-key="tab"', document)
        self.assertIn('id="mobile-navigation-mode"', document)
        self.assertIn('id="mobile-snapshot"', document)
        for key in ("home", "page-up", "page-down", "end", "delete"):
            self.assertIn(f'data-navigation-key="{key}"', document)
        self.assertIn('id="mobile-mouse-mode"', document)
        self.assertIn('aria-pressed="false" data-mode="off"', document)
        self.assertIn('data-mode-icon="on"', document)
        self.assertIn('data-mode-icon="off"', document)
        self.assertIn('class="mobile-bar-icon mobile-pointer-icon"', document)
        self.assertIn('M4.037 4.688a.495.495', document)
        self.assertIn('M22 2 2 22', document)
        self.assertTrue((STATIC_DIRECTORY / "icons" / "LUCIDE.LICENSE").is_file())
        self.assertNotIn("Clipboard mode", document)
        self.assertIn('id="mobile-keyboard-lock"', document)
        self.assertIn('data-lock-icon="locked"', document)
        self.assertIn('data-lock-icon="unlocked"', document)
        for direction in ("left", "up", "down", "right"):
            self.assertIn(f'data-arrow="{direction}"', document)
        self.assertIn("function applyMobileModifiers(data)", application)
        self.assertIn("if (data === '\\r') return terminalDataForModifiedEnter", application)
        self.assertIn("function physicalModifiedEnterData(event)", application)
        self.assertIn("function sendMobileArrow(direction)", application)
        self.assertIn("function sendMobileTerminalKey(key)", application)
        self.assertIn("function sendMobileNavigationKey(key)", application)
        self.assertIn("terminalDataForNavigationKey(key, mobileModifierState)", application)
        self.assertIn("mobileKeyRepeatInterval = setInterval(send, 70)", application)
        self.assertIn("let retainedKeyboardPane", application)
        self.assertIn("button.addEventListener('touchstart'", application)
        self.assertIn("if (event.pointerType !== 'touch')", application)
        self.assertIn("if (event.cancelable) event.preventDefault()", application)
        self.assertIn("button.addEventListener('mousedown', (event) => event.preventDefault())", application)
        self.assertIn("if (pane && pane === selectedPaneTerminal()) focusPaneKeyboard(pane)", application)
        self.assertIn("function terminalZoomControls()", application)
        self.assertIn("'herdr-web-mobile-terminal-font-size'", application)
        self.assertIn("fontSize: paneCompact ? mobileTerminalFontSize", application)
        self.assertIn("pane.terminal.options.fontSize = nextSize", application)
        self.assertIn("sheetHeading('Terminal size'), terminalZoomControls()", application)
        self.assertNotIn("function renderClipboardSheet()", application)
        self.assertNotIn("Copy selection or screen", application)
        self.assertNotIn("Paste text…", application)
        self.assertNotIn("document.createElement('textarea')", application)
        self.assertIn("function fitPaneTerminal(pane)", application)
        self.assertIn("--pane-terminal-remainder", application)
        self.assertIn("function sendTerminalMouseClick(pane, button, clientX, clientY)", application)
        self.assertIn("function sendTerminalMouseReport(pane, button, clientX, clientY", application)
        self.assertIn("function queuePaneMouseClick(pane, buttonCode, point)", application)
        self.assertIn("kind: 'pane-mouse'", application)
        self.assertIn("type: 'pane-mouse'", application)
        self.assertIn("action: 'click'", application)
        self.assertIn("MOBILE_LONG_PRESS_MS = 500", application)
        self.assertIn("MOBILE_MOUSE_DRAG_HOLD_MS = 180", application)
        self.assertIn("PANE_SCROLL_FLUSH_MS = 50", application)
        self.assertIn("PANE_SCROLL_FRAME_TIMEOUT_MS = 120", application)
        self.assertIn("let mobileMouseMode = false", application)
        self.assertIn("mobileMouseMode = false;", application)
        self.assertIn("touchMouseGesture = held < MOBILE_MOUSE_DRAG_HOLD_MS", application)
        self.assertIn("function flushPaneScroll(pane, force = false)", application)
        self.assertIn("if (mobileMouseMode && touchMouseGesture", application)
        self.assertIn("'Mouse input off; Paste is available'", application)
        self.assertNotIn("Clipboard mode", application)
        self.assertNotIn("MOBILE_CLIPBOARD_SCROLL_MOVE_PX", application)
        self.assertNotIn("classifyClipboardTouchMove(", application)
        self.assertNotIn("clipboardTouchGesture", application)
        self.assertIn("rightClickSelectsWord: false", application)
        self.assertNotIn("function terminalSelectionPoint(pane, clientX, clientY)", application)
        self.assertNotIn("function selectTerminalTouchRange(pane, start, end)", application)
        self.assertNotIn("function copyTerminalSelection(pane)", application)
        self.assertNotIn("ownerDocument.execCommand('copy')", application)
        self.assertIn("function queuePaneTextPaste(pane, text)", application)
        self.assertIn("normalizeTerminalPasteText(text)", application)
        self.assertIn("kind: 'pane-paste'", application)
        self.assertIn("type: 'pane-paste'", application)
        self.assertIn("event.inputType !== 'insertFromPaste'", application)
        self.assertIn("Turn mouse input off to Paste", application)
        self.assertIn("sendClipboardImage(image, record)", application)
        self.assertIn("stream_id: operation.streamId", application)
        self.assertNotIn("Herdr's pane API has no image input", application)
        self.assertNotIn("sendTerminalMouseClick(record, 0, event.clientX, event.clientY)", application)
        self.assertNotIn("clipboardOverlay", application)
        self.assertNotIn("terminal-native-clipboard", stylesheet)
        self.assertIn("ownerDocument.getSelection()", application)
        self.assertNotIn("cursorInput = document.createElement('input')", application)
        self.assertIn("function syncPaneKeyboardHelper(pane)", application)
        self.assertIn("function focusPaneKeyboard(pane)", application)
        self.assertIn("function handleMobileTerminalKeyDown(event)", application)
        self.assertIn("terminalDataForRepeatedMobileBackspace(pane.mobileBackspaceCount)", application)
        self.assertIn("MOBILE_BACKSPACE_RESET_MS = 400", application)
        self.assertIn("function handleMobileTerminalBeforeInput(event)", application)
        self.assertIn("terminalDataForBeforeInput(event.inputType)", application)
        self.assertIn("document.addEventListener('keydown', handleMobileTerminalKeyDown, true)", application)
        self.assertIn("document.addEventListener('beforeinput', handleMobileTerminalBeforeInput, true)", application)
        self.assertIn("pane.terminal.buffer.active.cursorX", application)
        self.assertIn("pane.terminal.buffer.active.cursorY", application)
        self.assertIn("sendTerminalMouseClick(record, 0, touchPointerX, touchPointerY);", application)
        self.assertIn("focusPaneKeyboard(record);", application)
        self.assertIn("touchDuration < MOBILE_LONG_PRESS_MS", application)
        self.assertIn("if (mobileKeyboardLocked || pane.mode", application)
        self.assertIn("function setMobileKeyboardLocked(locked", application)
        self.assertIn("if (!paneCompact) selectedRecord.terminal.focus()", application)
        self.assertIn("function focusTerminalAfterControl()", application)
        self.assertIn("dataset.mobileKeyboard !== 'open'", application)
        self.assertIn("const keyboardFocused = document.activeElement === paneKeyboardHelper(pane)", application)
        self.assertIn("focusPaneKeyboard(pane);", application)
        self.assertIn("function syncVisualViewportLayout()", application)
        self.assertIn("MOBILE_KEYBOARD_MINIMUM_SHRINK_PX = 120", application)
        self.assertIn("root.dataset.mobileKeyboard = keyboardOpen ? 'open' : 'closed'", application)
        self.assertIn("window.visualViewport?.addEventListener('resize'", application)
        self.assertIn("--visual-viewport-height", stylesheet)
        self.assertIn("--mobile-control-bottom-clearance", stylesheet)
        self.assertIn(':root[data-mobile-keyboard="closed"]', stylesheet)
        self.assertIn(':root[data-mobile-keyboard="open"]', stylesheet)
        self.assertIn("left: calc(var(--visual-viewport-left) + .5rem);", stylesheet)
        self.assertIn("max-width: calc(var(--visual-viewport-width) - 1rem);", stylesheet)
        self.assertIn("var(--visual-viewport-top) + env(safe-area-inset-top)", stylesheet)
        self.assertIn("#web-toasts {", stylesheet)
        self.assertIn("pointer-events: none;", stylesheet)
        self.assertIn(".web-toast:not(.clipboard-retry)", application)
        self.assertIn("const IOS_KEYBOARD_FONT_SIZE = 16", application)
        self.assertIn("MOBILE_NATIVE_MENU_CLICK_SUPPRESSION_MS = 750", application)
        self.assertIn("const targetWidth = nativePasteTarget ? screenBounds.width : 1", application)
        self.assertIn("const targetHeight = Math.max(1, cellHeight)", application)
        self.assertIn("const targetLeft = nativePasteTarget ? screenLeft : cursorLeft", application)
        self.assertIn("'mobile-native-paste-target', nativePasteTarget", application)
        self.assertIn("suppressClipboardClickUntil", application)
        self.assertIn("preserveClipboardFocusUntil", application)
        self.assertIn("event.button === 2 || performance.now() < preserveClipboardFocusUntil", application)
        self.assertIn(".xterm-helper-textarea.mobile-keyboard-target", stylesheet)
        self.assertIn(".mobile-native-paste-target", stylesheet)
        self.assertIn("opacity: 0;", stylesheet)
        self.assertIn("opacity: 1;", stylesheet)
        self.assertIn("pointer-events: auto;", stylesheet)
        self.assertIn("box-shadow: none;", stylesheet)
        self.assertNotIn(".terminal-cursor-input", stylesheet)
        self.assertNotIn("terminal-selection-actions", document)
        self.assertIn('aria-label="Back to sessions"', document)
        self.assertIn("function syncPaneConnectionStatus()", application)
        self.assertIn("pane.connection.disabled = !canReconnect", application)
        self.assertIn("function requestReconnect()", application)
        self.assertIn("function requiresAuthentication(response)", application)
        self.assertIn("function beginAuthenticationReload()", application)
        self.assertIn("function reloadForAuthentication(response)", application)
        self.assertIn("function recoverPaneWebSocket(backend)", application)
        self.assertIn("response.type === 'opaqueredirect'", application)
        self.assertIn("if (reloadForAuthentication(response))", application)
        self.assertIn("setStatus('Authentication expired', 'disconnected')", application)
        self.assertIn("connection.className = 'pane-connection'", application)
        self.assertNotIn("reconnect.textContent = 'Reconnect terminal'", application)
        self.assertIn("button:focus-visible { background: var(--theme-surface-1); outline: none; }", stylesheet)
        self.assertIn("@media (hover: hover) and (pointer: fine)", stylesheet)
        self.assertIn("button:hover { background: var(--theme-surface-1); outline: none; }", stylesheet)
        self.assertNotIn("button:hover, button:focus-visible", stylesheet)
        self.assertIn("-webkit-touch-callout: none;", stylesheet)
        self.assertIn("touch-action: none;", stylesheet)
        self.assertIn("#pane-grid .pane-terminal .xterm-rows", stylesheet)
        self.assertIn("-webkit-user-select: none !important;", stylesheet)
        self.assertIn(".pane-snapshot-view .xterm-rows", stylesheet)
        self.assertIn("-webkit-user-select: text !important;", stylesheet)
        self.assertIn("function captureTerminalSnapshot(source)", application)
        self.assertIn("function openTerminalSnapshot(pane)", application)
        self.assertIn("function closeTerminalSnapshot(pane, syncControls = true)", application)
        self.assertIn("function renderMobileSnapshotButton(active)", application)
        self.assertNotIn("snapshotButton.className = 'pane-snapshot'", application)
        self.assertIn("disableStdin: true", application)
        self.assertIn("snapshotTerminal.write(capture.ansi", application)
        self.assertIn("pane.snapshot = { terminal: snapshotTerminal, view }", application)
        self.assertIn("pane?.snapshot) return undefined", application)
        self.assertIn("selectedPaneTerminal()?.snapshot", application)
        self.assertIn(".pane-snapshot-view .xterm-rows", stylesheet)
        self.assertIn("--terminal-row-4: 72px", stylesheet)
        self.assertIn("grid-template-rows: repeat(2, var(--terminal-row-2))", stylesheet)
        self.assertIn("touch-action: manipulation;", stylesheet)

    def test_panes_mode_uses_structured_layout_and_one_multiplexed_socket(self) -> None:
        application = (STATIC_DIRECTORY / "app.js").read_text(encoding="utf-8")
        document = (STATIC_DIRECTORY / "index.html").read_text(encoding="utf-8")

        self.assertIn('id="panes-mode"', document)
        self.assertIn('id="pane-grid"', document)
        self.assertIn('id="pane-browse"', document)
        self.assertIn("type: 'panes.attach'", application)
        self.assertIn("navigationSnapshot?.layouts", application)
        self.assertIn("PANE_FRAME_MAGIC", application)
        self.assertIn("stream_id: pane.streamId", application)
        self.assertIn("Queued input was discarded because this pane is read-only", application)
        self.assertIn("pendingPaneActivation = streamId", application)
        self.assertIn("function refreshPaneTitles()", application)
        self.assertIn("refreshPaneTitles();", application)
        self.assertIn("record?.agent_status", application)
        self.assertIn("function paneStructureFingerprint(snapshot, tabId)", application)
        self.assertIn("function schedulePaneStructureRebuild()", application)
        self.assertIn("inputBuffer.length || inputOperations.length || pendingMouseMotion", application)
        self.assertIn("function paneAcceptsInput(pane, announce = true)", application)
        self.assertIn("pane.terminal.options.disableStdin = true", application)
        self.assertIn("pane.mode === 'control' && !pane.closed", application)

    def test_xterm_contains_synchronized_output_render_fix(self) -> None:
        xterm = (STATIC_DIRECTORY / "vendor" / "xterm.js").read_text(
            encoding="utf-8"
        )

        self.assertIn(
            "s?this._renderRows(e,t):this._renderDebouncer.refresh(e,t,this._rowCount)",
            xterm,
        )
        self.assertTrue(
            (STATIC_DIRECTORY / "vendor" / "xterm.SYNC-OUTPUT-PATCH.md").is_file()
        )

    def test_xterm_contains_mobile_paste_fixes(self) -> None:
        application = (STATIC_DIRECTORY / "app.js").read_text(encoding="utf-8")
        stylesheet = (STATIC_DIRECTORY / "vendor" / "xterm.css").read_text(
            encoding="utf-8"
        )
        xterm = (STATIC_DIRECTORY / "vendor" / "xterm.js").read_text(
            encoding="utf-8"
        )

        self.assertIn(
            'e.clipboardData&&(e.preventDefault(),r(e.clipboardData.getData("text/plain")',
            xterm,
        )
        self.assertIn(
            '_inputEvent(e){if("insertFromPaste"===e.inputType&&this.textarea?.value)',
            xterm,
        )
        self.assertIn("return pane?.terminal.textarea;", application)
        self.assertNotIn(
            "terminal.element?.querySelector('.xterm-helper-textarea')",
            application,
        )
        self.assertIn(".xterm .xterm-width-cache-measure-container", stylesheet)
        self.assertTrue(
            (STATIC_DIRECTORY / "vendor" / "xterm.MOBILE-PASTE-PATCH.md").is_file()
        )


if __name__ == "__main__":
    unittest.main()
